version: "3.5"

services:
  
  app: 
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DB_NAME: cars_db
      DB_USER: root
      DB_PASS: root
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 8000:8000
  
  db:
      image: "postgres:13.0"
      hostname: db
      environment:
        POSTGRES_PASSWORD: "root"
        POSTGRES_USER: "root"
        POSTGRES_DB: "cars_db"
      ports:
        - "5432:5432"
