# Generated by Django 3.1.5 on 2021-01-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_avg_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='make',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('make', 'model')},
        ),
    ]
