# Generated by Django 3.1.5 on 2021-01-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20210109_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='avg_rate',
            field=models.FloatField(default=0, null=True),
        ),
    ]
