# Generated by Django 3.1.5 on 2021-01-09 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_car_rate_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('rate_count',)},
        ),
    ]
